# Generated by Django 2.0.1 on 2018-01-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_url', models.CharField(max_length=4000)),
                ('offer_price', models.IntegerField()),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('dealer_phone', models.CharField(max_length=32)),
                ('dealer_name', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField()),
                ('sell_date', models.DateTimeField(null=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
